.github/workflows/ci.yml

This is loosely based on two of my other project's actions
https://github.com/elixir-sqlite/ecto_sqlite3/blob/main/.github/workflows/ci.yml
Right now the lint action does not do much, but as the project progresses, the steps / checks there can be enabled.
Locally I have 4 tests failing and the last run is vomiting errors https://github.com/warmwaffles/image/actions/runs/2349600899

Adds github actions

---

lib/image.ex

According to the docs it should be possible to pass a width and height to `Image.resize` as second argument in this format: `"<width>x<height>"`. However when doing this Dialyzer will complain since the specs don't reflect this. This pull-requests updates the specs for `Image.resize` and `Image.resize!`.
*Note: as a workaround I currently pass width as an integer and use the optional height option. `Image.resize("path", 200, height: 100)`*

Update specs for Image.resize

---

test/support/image_test_helpers.ex

Right now, the tests check "is the `computed image` under test **exactly equal** to some pre-rendered `verification image`?". This exact equality check is reasonable, but it's failing right now. Why? 
Because we use changing versions of the `libvips` library, sometimes our pre-rendered image verification images can get out of sync with computed images under test. They'd be similar enough, but the changes upstream are enough that our pre-renders are not _exactly equal_ to computed images.
This PR is a stopgap, where we define a passing test as when "images are similar _enough_". Empirically, the threshold is 97% similar.
Better solutions exist. Off the top of my head, they might include: 
- keeping the pre-renders up to date with some automated job, requiring update any time a dependency …

Make tests pass based on a threshold instead of absolute match

---

lib/image/options/meme.ex

I think `:ultralight` was missing since it is listed in the doc:
The options are `:ultralight`,  `:light`, `:normal`, `:bold`, `:ultrabold` or `:heavy`. The default is `:bold`.

Adding :ultralight option for the meme function

---

lib/image/options/thumbnail.ex

I had a BadMapError when trying to use the :intent option with `Image.thumbnail!/3` because `options` is a Keyword and not a Map.

Fix BadMapError for the :intent option in thumbnail.ex

---

lib/image.ex
lib/image/options/write.ex

I would like to add the :effort option which adjusts the cpu effort.
I found it very useful to write `.avif` files, because the default option makes it quite slow.
This option is available for `png`, `heif`, `webp`, `gif` and maybe more formats (but not for `jpg` and `tiff`).

Add :effort option

---

lib/image.ex
lib/image/options/write.ex

I added a `:minimize_file_size` option for the `webp` format.
To be honest, on my test it did not change anything regarding the file size and the strip doesn't seems to strip any metadata unlike for other formats, but this is not related to `Image` because I have the same result using [Vix](https://github.com/akash-akya/vix).
Maybe it works only on some images, or there is an issue with Vix or libvips.
I'll make some more test later and see.

Add :minimize_file_size for webp

---

lib/image/options/write.ex

Apparently, the High Efficiency Image File Format actually concern multiple file extensions such as **heif**, **heic** and **avif**.
But for now, I think there is an issue with **Vix** because it's only possible to write **avif** files.
```elixir
iex> "image.jpg" |> Image.open!() |> Image.write("image.heif")
{:error, "Failed to write VipsImage to file"}
iex> "image.jpg" |> Image.open!() |> Image.write("image.heic")
{:error, "Failed to write VipsImage to file"}
iex> "image.jpg" |> Image.open!() |> Image.write("image.avif")
{:ok, %Vix.Vips.Image{ref: #Reference<0.1081433751.827981858.88616>}}
iex> {:ok, image} = Vix.Vips.Image.new_from_file("image.jpg")
{:ok, %Vix.Vips.Image{ref: #Reference<0.1081433751.827981858.88598>}}
iex> Vix.Vips.Image.write_to_file(image, "image.heif")
{:error, …
```

fix conform effort to add .avif and .heic support

---

lib/image.ex
lib/image/options/open.ex
lib/image/options/write.ex

- Add a new `interframe_maxerror` parameter for GIFs which allow to increase compression of the frames of the GIF
- Update the `pages` option to allow the use from `-1` which allow to select all the pages of the animated image
- Some minor changes

Multiple changes for animated images

---

lib/image/options/open.ex

The previous default pages paramater I added is actually breaking the open for formats not having this parameter such as `jpg`.
As I don't know how to do this properly, we should just remove this for now.

Remove pages default parameter

---

lib/image.ex

The write options did not mach the the write options in https://github.com/elixir-image/image/blob/main/lib/image/options/write.ex#L38 there are probably more but these are the two I noticed. I'm honestly not certain where color_depth came from but I'm not a VIPS expert.

Update Image.write options documentation to match the code.

---

test/stream_image_test.exs

Hey Kip, this is a very small PR to fix a compile warning when `minio` isn't installed (`@s3_buffer_size is set but never used`).  I'm working on the hotspot PR!

Fix warning when minio is not installed

---

lib/image.ex

Currently passing something like `[x: center, y: 1_000]` throws an error although Vix allows this.  This proposed commit fixes this.
There were no tests around this function so I have not added any.  If you are interested I'd be happy to write some tests around this function in general.

Allow mixing int and atom values in compose's xy_offsets

---

lib/image/options/text.ex
lib/image/text.ex

This commit adds the `:letter_spacing` option to text functions.  I had originally called it `:tracking` as that is the more technical term but decided to go with what CSS does and is the most understandable.  Happy to rename it to whatever you see fit.

Add `:letter_spacing` option to text functions

---

lib/image.ex
test/nx_interop_test.exs

Currently when converting an `nx` tensor to Image we only check for the shape and we assume it's `{width, height, bands}`. So an example like this will fail:
```elixir
image = Image.open!("image.jpeg")
{:ok, tensor} = Image.to_nx(image, shape: :hwc)
{:ok, image2} = Image.from_nx(tensor)
```
In this example `image2` is not the same as `image` and will have its `width` and `height` values swapped.
In this PR, we also check if the name of the first axis of the tensor is `height`, if it's the case, then the `width` and `height` values will be swapped.

Check axis names on converting nx tensor to image

---

lib/image.ex

A fix to the returns section for the `feather!` function doc.

Fix feather! returns doc

---

lib/image.ex
lib/image/text.ex

Hi ! 
This small Pull Request is to fix what I believe was a typo (`impage` instead of `image`).
That's it, Thanks !

docs: fixed tiny typo

---

lib/image.ex

An error occurs when executing the contrast function

fix: Fix the bug in the contrast function

---

lib/application.ex

Currently, the `Image.Classification` module is loaded when `Bumblebee`, `Nx` and `Exla` are available. However, `Image.Application` calls `Image.Classification` when `Bumblebee` is available. So, if one has `Bumblebee` in deps, but not `Exla`, this error is raised:
```elixir
** (Mix) Could not start application image: exited in: Image.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (UndefinedFunctionError) function Image.Classification.classifier/0 is undefined (module Image.Classification is not available)
Image.Classification.classifier()
(image 0.54.1) lib/application.ex:34: anonymous fn/2 in Image.Application.children/1
(elixir 1.17.2) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
(image 0.54.1) lib/application.ex:18: Image.Application.start/2
(kernel …
```

Fix bumblebee detection

---

.github/workflows/ci.yml
mix.exs

I was trying to [update image on a project](https://github.com/BeaconCMS/beacon/actions/runs/10775052364/job/29878588843?pr=586) but it failed with:
```
== Compilation error in file lib/image/exif/decode.ex == Error: ** (CompileError) lib/image/exif/decode.ex:138: size in bitstring expects an integer or a variable as argument, got: :erlang.*(:erlang.byte_size(value), 8)
```
Which was introduce in https://github.com/elixir-image/image/commit/855dfacd5c83761435a3c3d521f9bdff3ead7944, but then working on a fix I realized I was not able to compile it due not meeting Nx requirements:
```
==> nx
warning: the dependency :nx requires Elixir "~> 1.14" but you are running on v1.12.3
Error while loading project :nx
** (Mix) Nx requires Erlang/OTP 24+
```
Since `image` optionally depends on Nx, it …

Bump minimum Elixir version to 1.14

---

lib/image/text.ex

Drop mention of background_fill_color, as it is not evaluated.
Closes #167.

Make docs for Draw.simple_text less confusing

---

lib/image/exif/decode.ex

Two small tweaks to support images I have encountered from smartphones
* `datetime_original_offset` and `datetime_digitized_offset` which is the offsets for `datetime_original` and `datetime_digitized`
* Alternate encoding of tags which return `version`. This crashed before this change.

Small improvements to exif data decoding

---

lib/image.ex

`pixelate!/1` had a partly copy-pasted doc string from `pixelate/1`

Fix typo in doc string

---

lib/image/exif/decode.ex

The EXIF non-standard strikes again, and I have found another quirk.
Some smartphones seem to produce datetime strings a null byte appended. We can deal with this by stripping trailing null bytes before attempting conversion to integer.

handle datetimes with appended null bytes in exif

---

lib/image.ex

From [the Stream documentation][1]:
> #### Do not check for `Stream` structs
>
> While some functions in this module may return the `Stream` struct,
> you must never explicitly check for the `Stream` struct, as streams
> may come in several shapes, such as `IO.Stream`, `File.Stream`, or
> even `Range`s.
>
> The functions in this module only guarantee to return enumerables
> and their implementation (structs, anonymous functions, etc) may
> change at any time. For example, a function that returns an anonymous
> function today may return a struct in future releases.
>
> Instead of checking for a particular type, you must instead write
> assertive code that assumes you have an enumerable, using the functions
> in the `Enum` or `Stream` module accordingly.
`open/2` currently pattern matches …

open/2: accept generic Enumerables

---

lib/image/exif/decode.ex

This commit adds more EXIF tags:
- Lens (0xFDEA)
- ImageNumber (0x9211)
- ImageTitle (0xA436)
- CameraLabel (0xC7A1)
It also re-arranges other EXIF function clauses to be in numeric order

add more EXIF tags, put other EXIF clauses in order
